runtime: nodejs20
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  NODE_ENV: "production"

handlers:
  # 매니페스트 파일 처리 (빌드 ID 포함)
  - url: /_next/static/([^/]+)/(_buildManifest\.js|_ssgManifest\.js)
    static_files: .next/static/\1/\2
    upload: .next/static/[^/]+/(_buildManifest\.js|_ssgManifest\.js)
    secure: always
    expiration: "30d"
  
  # 루트 레벨 매니페스트 파일 처리 (빌드 ID 없음)
  - url: /_next/(_buildManifest\.js|_ssgManifest\.js)
    static_files: .next/\1
    upload: .next/(_buildManifest\.js|_ssgManifest\.js)
    secure: always
    expiration: "30d"

  # 앱 청크 파일 처리
  - url: /_next/static/chunks/pages/(_app-[^/]+\.js)
    static_files: .next/static/chunks/pages/\1
    upload: .next/static/chunks/pages/(_app-[^/]+\.js)
    secure: always
    expiration: "360d"
    
  # 청크 파일 처리
  - url: /_next/static/chunks/([^/]+)
    static_files: .next/static/chunks/\1
    upload: .next/static/chunks/([^/]+)
    secure: always
    expiration: "360d"
  
  # 일반 Next.js 정적 파일 처리
  - url: /_next/static/(.*)
    static_files: .next/static/\1
    upload: .next/static/(.*)
    secure: always
    expiration: "360d"
    
  # Next.js 페이지 데이터 파일 제공
  - url: /_next/data/(.*)
    static_files: .next/data/\1
    upload: .next/data/(.*)
    secure: always
    
  # Next.js 루트 파일 처리 (js, json 등)
  - url: /_next/([^/]+\.js)
    static_files: .next/\1
    upload: .next/([^/]+\.js)
    secure: always
    expiration: "30d"
    
  # public 정적 파일 처리
  - url: /(.*\.(ico|png|jpg|jpeg|gif|svg|css|js))
    static_files: public/\1
    upload: public/.*\.(ico|png|jpg|jpeg|gif|svg|css|js)
    secure: always
    expiration: "7d"

  # 기본 핸들러
  - url: /.*
    script: auto
    secure: always

service: default 