name: Deploy to Google App Engine

on:
  push:
    branches:
      - master

# Deploy workflow after adding permissions
jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install --frozen-lockfile
        
      - name: Cache Next.js build
        uses: actions/cache@v3
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
          
      - name: Build
        run: npm run build

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
          export_environment_variables: true
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Print auth info
        run: |
          echo "Using service account: $GCLOUD_SERVICE_ACCOUNT"
          gcloud config list
          
      - name: Deploy to App Engine
        run: |
          echo "*** Starting deployment ***"
          gcloud app deploy app.yaml --quiet --promote --project=${{ secrets.GCP_PROJECT_ID }}
